name: recsys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - streamlit
  - statsmodels
  - pip
  - pip:
      - lightfm
      - nmslib