name: recsys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - lightfm
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - streamlit
  - nmslib
  - statsmodels
